
import os

PROYECT_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__))).replace("\\", "/")
CODE_PATH = PROYECT_PATH + "/Code"
SHOT_CLASSIFICATION_CODE_PATH = CODE_PATH + "/shot_classification"
TRANSNET_PATH = CODE_PATH + "/shot_boundary_detection/transnetv2/inference-pytorch"
DATA_PATH = PROYECT_PATH + "/Data"
MODELING_DATA_PATH = DATA_PATH + "/Modeling"
RAW_DATA_PATH = DATA_PATH + "/Raw"
VIDEOS_RAW_DATA_PATH = RAW_DATA_PATH + "/Videos/ShotBoundaryVideos"
PROCESSED_DATA_PATH = DATA_PATH + "/Processed"
VIDEOCUTS_PROCESSED_DATA_PATH = PROCESSED_DATA_PATH + "/videoCuts"
FACIAL_REC_PROCESSED_DATA_PATH = PROCESSED_DATA_PATH + "/facial_recognition"
FACIAL_INTERVENTIONS_PROCESSED_DATA_PATH = FACIAL_REC_PROCESSED_DATA_PATH + "/InterventionsFiles"
VOCAL_REC_PROCESSED_DATA_PATH = PROCESSED_DATA_PATH + "/vocal_recognition"
VOCAL_INTERVENTIONS_PROCESSED_DATA_PATH = VOCAL_REC_PROCESSED_DATA_PATH + "/InterventionsFiles"
VIDEO_AUDIOS_VOCAL_REC_PROCESSED_DATA_PATH = VOCAL_REC_PROCESSED_DATA_PATH + "/VideoAudios"
FULL_AUDIOS_VOCAL_REC_PROCESSED_DATA_PATH = VIDEO_AUDIOS_VOCAL_REC_PROCESSED_DATA_PATH + "/FullAudios"
INTERVENTIONS_VOCAL_REC_PROCESSED_DATA_PATH = VOCAL_REC_PROCESSED_DATA_PATH + "/"
INTERVENTIONS_AUDIOS_VOCAL_REC_PROCESSED_DATA_PATH = VIDEO_AUDIOS_VOCAL_REC_PROCESSED_DATA_PATH + "/Interventions"
MAX_CROP_TIME_SECONDS = 10
MIN_INTERVENTION_TIME_SECONDS = 3
FFMPEG_PATH = CODE_PATH + "/installing/ffmpeg/bin"
PYANNOTE_AUTH_TOKEN = "INTRODUZCA AQUÍ SU TOKEN DE AUTENTICACIÓN DE PYANNOTE.AUDIO"
OPENAI_API_KEY = "INTRODUZCA AQUÍ SU API_KEY DE PAGO DE OPENAI"
SUMMARIES_PROCESSED_DATA_PATH = PROCESSED_DATA_PATH + "/video_summaries"
